server:
  port: 8081
  servlet:
    context-path: /oxygenshow/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oxygenshow?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: root
      password: 111111